annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Add missing import if allowedHostsIncludesPodIp is true
      links:
        - name: GitHub Pull Request
          url: https://github.com/startechnica/apps/pull/68
    - kind: changed
      description: Update Netbox Docker to v2.8.0
      links:
        - name: GitHub Releases
          url: https://github.com/netbox-community/netbox-docker/releases/tag/2.8.0
    - kind: changed
      description: Update Netbox v3.7.8
      links:
        - name: GitHub Releases
          url: https://github.com/netbox-community/netbox/releases/tag/v3.7.8
  licenses: Apache-2.0
  images: |
    - name: netbox
      image: docker.io/netboxcommunity/netbox:v3.7.8-2.8.0
apiVersion: v2
appVersion: v3.7.8
name: netbox
kubeVersion: ">=1.25.0"
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
home: https://github.com/startechnica/apps/tree/main/charts/netbox
icon: https://raw.githubusercontent.com/netbox-community/netbox/develop/docs/netbox_logo.png
maintainers:
- name: Firmansyah Nainggolan
  email: firmansyah@nainggolan.id
  url: https://firmansyah.nainggolan.id
dependencies:
- name: postgresql
  version: 13.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
- name: redis
  version: 19.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
  tags:
    - bitnami-common
  alias: bitnami-common
- name: st-common
  repository: https://startechnica.github.io/apps
  version: 0.x.x
  alias: startechnica-common
keywords:
  - ipam
  - netbox
type: application
version: 5.0.9