{{- /*
(c) 2025 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.appsec.storage.serviceAccount.create .Values.appsec.storage.enabled (not .Values.playground.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "open-appsec.storage.serviceAccountName" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- if or .Values.appsec.storage.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := include "st-common.tplvalues.merge" ( dict "values" ( list .Values.appsec.storage.serviceAccount.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "st-common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.appsec.storage.serviceAccount.automountServiceAccountToken }}
{{- end }}
