annotations:
  category: Infrastructure
  artifacthub.io/changes: |
    - kind: changed
      description: Fix Istio API resources
apiVersion: v2
appVersion: 0.1.7
description: A Library Helm Chart for grouping common logic between Startechnica charts.
  This chart is not deployable by itself.
home: https://github.com/startechnica/apps/tree/main/charts/common
icon: https://startechnica.github.io/apps/images/star.png
keywords:
  - common
  - helper
  - template
  - function
kubeVersion: ">=1.20.0-0"
maintainers:
  - name: firmansyahn
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: st-common
sources:
  - https://startechnica.github.io/apps
type: library
version: 0.1.7