#####################################
## FreeRADIUS ConfigMap config
#####################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  FREERADIUS_ENABLE_TLS: {{ ternary "true" "false" .Values.tls.enabled | quote }}

  {{- if .Values.modsEnabled.sql.enabled }}
  FREERADIUS_MODS_SQL_DIALECT: {{ .Values.modsEnabled.sql.dialect }}
  FREERADIUS_MODS_SQL_SERVER: {{ include "freeradius.databaseHost" . | quote }}
  FREERADIUS_MODS_SQL_PORT: {{ include "freeradius.databasePort" . }}
  FREERADIUS_MODS_SQL_LOGIN: {{ include "freeradius.databaseUser" . | quote }}
  FREERADIUS_MODS_SQL_DB: {{ include "freeradius.databaseName" . | quote }}
  FREERADIUS_MODS_SQL_TABLE_ACCT1: {{ .Values.modsEnabled.sql.table.acct1 }}
  FREERADIUS_MODS_SQL_TABLE_ACCT2: {{ .Values.modsEnabled.sql.table.acct2 }}
  FREERADIUS_MODS_SQL_TABLE_AUTHCHECK: {{ .Values.modsEnabled.sql.table.authcheck }}
  FREERADIUS_MODS_SQL_TABLE_AUTHREPLY: {{ .Values.modsEnabled.sql.table.authreply }}
  FREERADIUS_MODS_SQL_TABLE_CLIENT: {{ .Values.modsEnabled.sql.table.client }}
  FREERADIUS_MODS_SQL_TABLE_GROUPCHECK: {{ .Values.modsEnabled.sql.table.groupcheck }}
  FREERADIUS_MODS_SQL_TABLE_GROUPREPLY: {{ .Values.modsEnabled.sql.table.groupreply }}
  FREERADIUS_MODS_SQL_TABLE_POSTAUTH: {{ .Values.modsEnabled.sql.table.postauth }}
  FREERADIUS_MODS_SQL_TABLE_USERGROUP: {{ .Values.modsEnabled.sql.table.usergroup }}
  FREERADIUS_MODS_SQL_TLS_ENABLE: {{ ternary "yes" "no" .Values.modsEnabled.sql.tls.enabled | quote }}
  {{- end }}

  FREERADIUS_SITES_DEFAULT_AUTH_PORT: {{ .Values.containerPorts.auth | quote }}
  FREERADIUS_SITES_DEFAULT_ACCT_PORT: {{ .Values.containerPorts.acct | quote }}
  {{- if .Values.sitesEnabled.coa.enabled }}
  FREERADIUS_SITES_COA_LISTEN: {{ .Values.sitesEnabled.coa.listen | quote }}
  FREERADIUS_SITES_COA_PORT: {{ .Values.sitesEnabled.coa.port | quote }}
  {{- end }}
  {{- if .Values.sitesEnabled.status.enabled }}
  FREERADIUS_SITES_STATUS_LISTEN: {{ .Values.sitesEnabled.status.listen | quote }}
  FREERADIUS_SITES_STATUS_PORT: {{ .Values.containerPorts.status | quote }}
  {{- end }}
    {{- if .Values.tls.enabled }}
  FREERADIUS_SITES_TLS_LISTEN: {{ .Values.sitesEnabled.tls.listen | quote }}
  FREERADIUS_SITES_TLS_PORT: {{ .Values.containerPorts.radsec | quote }}
  FREERADIUS_SITES_TLS_PRIVKEY_PASSWORD: whatever
  FREERADIUS_SITES_TLS_PRIVKEY_FILE: {{ include "freeradius.tlsCertKey" . | quote }}
  FREERADIUS_SITES_TLS_CERTIFICATE_FILE: {{ include "freeradius.tlsCert" . | quote }}
  FREERADIUS_SITES_TLS_CA_FILE: {{ include "freeradius.tlsCACert" . | quote }}
  {{- end }}

