{{- /*
(c) 2025 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s:mutate-injection" (include "st-common.names.fullname" .) }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: open-appsec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s:mutate-injection" (include "st-common.names.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "open-appsec.webhook.serviceAccountName" . }}
    namespace: {{ include "st-common.names.namespace" . | quote }}
  - kind: ServiceAccount
    name: {{ include "open-appsec.tuning.serviceAccountName" . }}
    namespace: {{ include "st-common.names.namespace" . | quote }}