{{- /*
(c) 2025 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-appsec.names.secretName" . }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: open-appsec
data:
  {{- if .Values.agent.agentToken }}
  agent-token: {{ .Values.agent.agentToken | b64enc }}
  {{- end }}
  {{- if .Values.agent.userEmail }}
  user-email: {{ .Values.agent.userEmail | b64enc }}
  {{- end }}
