{{- /*
(c) 2025 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-appsec.webhook.serviceName" . | quote }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: open-appsec
  {{- if or .Values.webhook.service.annotations (and .Values.metrics.enabled .Values.metrics.service.annotations) .Values.commonAnnotations }}
  {{- $annotations := include "st-common.tplvalues.merge" ( dict "values" ( list .Values.webhook.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "st-common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  {{- if and (eq .Values.webhook.service.type "LoadBalancer") (not (empty .Values.webhook.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.webhook.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.webhook.service.type "LoadBalancer") (not (empty .Values.webhook.service.loadBalancerClass)) }}
  loadBalancerClass: {{ .Values.webhook.service.loadBalancerClass }}
  {{- end }}
  {{- if and (eq .Values.webhook.service.type "LoadBalancer") (not (empty .Values.webhook.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.webhook.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and .Values.webhook.service.clusterIP (eq .Values.webhook.service.type "ClusterIP") }}
  clusterIP: {{ .Values.webhook.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.webhook.service.type "LoadBalancer") (eq .Values.webhook.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.webhook.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if .Values.webhook.service.sessionAffinity }}
  sessionAffinity: {{ .Values.webhook.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.webhook.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "st-common.tplvalues.render" (dict "value" .Values.webhook.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.webhook.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if and (or (eq .Values.webhook.service.type "NodePort") (eq .Values.webhook.service.type "LoadBalancer")) (not (empty .Values.webhook.service.nodePorts.https)) }}
      nodePort: {{ .Values.webhook.service.nodePorts.https }}
      {{- else if eq .Values.webhook.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.webhook.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
      {{- if and (or (eq .Values.webhook.service.type "NodePort") (eq .Values.webhook.service.type "LoadBalancer")) (not (empty .Values.webhook.service.nodePorts.metrics)) }}
      nodePort: {{ .Values.webhook.service.nodePorts.metrics }}
      {{- else if eq .Values.webhook.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.webhook.service.extraPorts }}
    {{- include "st-common.tplvalues.render" (dict "value" .Values.webhook.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- $podLabels := include "st-common.tplvalues.merge" ( dict "values" ( list .Values.webhook.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "st-common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: webhook
