annotations:
  category: Networking
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/startechnica/apps/tree/main/charts/multus
    - name: Upstream Project
      url: https://github.com/k8snetworkplumbingwg/multus-cni
apiVersion: v2
appVersion: 4.0.2
dependencies:
  - name: st-common
    repository: https://startechnica.github.io/apps
    version: x.x.x
    alias: startechnica-common
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Multus CNI is a container network interface (CNI) plugin for Kubernetes
  that enables attaching multiple network interfaces to pods.
home: https://github.com/startechnica/apps/tree/main/charts/multus
icon: https://github.com/k8snetworkplumbingwg/multus-cni/raw/master/docs/images/Multus.png
keywords:
  - cni
  - multus
  - multus-cni
  - networkplumbing
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Firmansyah Nainggolan
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: multus-cni
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
version: 0.1.3