{{- /*
(c) 2025 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appsec.secretName | default "appsec-settings-secret" | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: open-appsec
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- if and .Values.crowdSec.enabled .Values.crowdSec.auth.data }}
  CROWDSEC_AUTH_DATA: {{ .Values.crowdSec.auth.data | b64enc }}
  {{- end }}
