annotations:
  category: DatabaseManagement
  artifacthub.io/images: |
    - name: adminer
      image: docker.io/adminer:4.8.1-standalone
apiVersion: v2
appVersion: 4.8.1
dependencies:
  - name: st-common
    repository: https://startechnica.github.io/apps
    version: "*"
    alias: startechnica-common
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
    tags:
      - bitnami-common
    alias: bitnami-common
description: Adminer is a full-featured database management tool written in PHP. Conversely
  to phpMyAdmin, it consist of a single file ready to deploy to the target server. Adminer
  is available for MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, Firebird, SimpleDB,
  Elasticsearch and MongoDB
home: https://github.com/startechnica/apps/tree/main/charts/adminer
icon: https://www.adminer.org/static/images/logo.png
keywords:
  - adminer
  - postgres
  - mysql
  - sqlite
  - elasticsearch
  - mongodb
  - database
  - sql
maintainers:
  - name: firmansyahn
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: adminer
sources:
  - https://www.adminer.org
type: application
version: 0.1.7