annotations:
  category: ServiceMesh
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/startechnica/apps/tree/main/charts/istio-ingress-gateway
    - name: Upstream Project
      url: https://github.com/istio/istio/tree/master/manifests/charts/gateways/istio-ingress
apiVersion: v2
appVersion: 1.13.4
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Istio Ingress Gateway provides more extensive customization and flexibility than 
  Kubernetes Ingress, and allows Istio features such as monitoring and route rules to be applied 
  to traffic entering the cluster.
home: https://github.com/startechnica/apps/tree/main/charts/istio-ingress-gateway
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
  - ingress
  - ingressgateway
kubeVersion: ">=1.19.0-0"
maintainers:
  - name: firmansyahn
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: istio-ingress-gateway
sources:
  - http://github.com/istio/istio
type: application
version: 0.1.0
