{{- /*
Copyright (c) 2025 Firmansyah Nainggolan. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freeradius.names.envvars" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "st-common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  FREERADIUS_ENABLE_TLS: {{ ternary "true" "false" .Values.tls.enabled | quote }}

  FREERADIUS_CLIENTS_SHORTNAME: ""
  FREERADIUS_CLIENTS_IPV4ADDR: ""
  FREERADIUS_CLIENTS_IPV6ADDR: ""
  FREERADIUS_CLIENTS_SECRET: ""

  {{- if .Values.modsEnabled.sql.enabled }}
  FREERADIUS_MODS_SQL_DIALECT: {{ .Values.modsEnabled.sql.dialect }}
  FREERADIUS_MODS_SQL_SERVER: {{ include "freeradius.database.host" . | quote }}
  FREERADIUS_MODS_SQL_PORT: {{ include "freeradius.database.port" . }}
  FREERADIUS_MODS_SQL_LOGIN: {{ include "freeradius.database.user" . | quote }}
  FREERADIUS_MODS_SQL_DB: {{ include "freeradius.database.name" . | quote }}
  FREERADIUS_MODS_SQL_TABLE_ACCT1: {{ .Values.modsEnabled.sql.table.acct1 }}
  FREERADIUS_MODS_SQL_TABLE_ACCT2: {{ .Values.modsEnabled.sql.table.acct2 }}
  FREERADIUS_MODS_SQL_TABLE_AUTHCHECK: {{ .Values.modsEnabled.sql.table.authcheck }}
  FREERADIUS_MODS_SQL_TABLE_AUTHREPLY: {{ .Values.modsEnabled.sql.table.authreply }}
  FREERADIUS_MODS_SQL_TABLE_CLIENT: {{ .Values.modsEnabled.sql.table.client }}
  FREERADIUS_MODS_SQL_TABLE_GROUPCHECK: {{ .Values.modsEnabled.sql.table.groupcheck }}
  FREERADIUS_MODS_SQL_TABLE_GROUPREPLY: {{ .Values.modsEnabled.sql.table.groupreply }}
  FREERADIUS_MODS_SQL_TABLE_POSTAUTH: {{ .Values.modsEnabled.sql.table.postauth }}
  FREERADIUS_MODS_SQL_TABLE_USERGROUP: {{ .Values.modsEnabled.sql.table.usergroup }}
  FREERADIUS_MODS_SQL_TLS_ENABLE: {{ ternary "yes" "no" .Values.modsEnabled.sql.tls.enabled | quote }}

  FREERADIUS_MODS_SQL_READ_CLIENTS: {{ ternary "yes" "no" .Values.modsEnabled.sql.readClients | quote }}
  FREERADIUS_MODS_SQL_GROUP_ATTRIBUTE: {{ .Values.modsEnabled.sql.groupAttribute | quote }}

  FREERADIUS_MODS_SQL_SQLITE_FILENAME: /startechnica/freeradius/freeradius.db
  FREERADIUS_MODS_SQL_SQLITE_BUSY_TIMEOUT: "200"

  {{- if .Values.modsEnabled.sql.tls.enabled }}
  FREERADIUS_MODS_SQL_TLS_CACERT: {{ include "freeradius.sqlTlsCACert" . | quote }}
  FREERADIUS_MODS_SQL_TLS_CIPHER: ""
  FREERADIUS_MODS_SQL_TLS_CERTIFICATE: {{ include "freeradius.sqlTlsCert" . | quote }}
  FREERADIUS_MODS_SQL_TLS_PRIVATEKEY: {{ include "freeradius.sqlTlsCertKey" . | quote }}
  FREERADIUS_MODS_SQL_TLS_PRIVATEKEY_PASSWORD: whatever
  {{- end }}
  {{- end }}

  FREERADIUS_SITES_NAMESPACE: radius

  FREERADIUS_SITES_DEFAULT_AUTH_PORT: {{ .Values.containerPorts.auth | quote }}
  FREERADIUS_SITES_DEFAULT_ACCT_PORT: {{ .Values.containerPorts.acct | quote }}
  {{- if .Values.sitesEnabled.coa.enabled }}
  FREERADIUS_SITES_COA_PORT: {{ .Values.containerPorts.coa | quote }}
  {{- end }}
  {{- if .Values.sitesEnabled.status.enabled }}
  FREERADIUS_SITES_STATUS_LISTEN: {{ .Values.sitesEnabled.status.listen | quote }}
  FREERADIUS_SITES_STATUS_PORT: {{ .Values.containerPorts.status | quote }}
  {{- end }}
  {{- if .Values.sitesEnabled.tls.enabled }}
  FREERADIUS_SITES_TLS_PORT: {{ .Values.containerPorts.radsec | quote }}
  FREERADIUS_SITES_TLS_CA_FILE: {{ include "freeradius.tlsCACert" . | quote }}
  FREERADIUS_SITES_TLS_CERTIFICATE_FILE: {{ include "freeradius.tlsCert" . | quote }}
  FREERADIUS_SITES_TLS_CIPHER: {{ default "DEFAULT" .Values.sitesEnabled.tls.cipher | quote }}
  FREERADIUS_SITES_TLS_PRIVKEY_FILE: {{ include "freeradius.tlsCertKey" . | quote }}
  {{- end }}