{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecretName) (not .Values.tasksRedis.existingSecretName) (not .Values.cachingRedis.existingSecretName) (not .Values.redis.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "netbox.fullname" .) "external-redis" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.externalRedis.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.externalRedis.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "netbox.cachingRedis.secretPasswordKey" . }}: {{ include "netbox.cachingRedis.password" . }}
  {{ include "netbox.tasksRedis.secretPasswordKey" . }}: {{ include "netbox.tasksRedis.password" . }}
{{- end -}}
